apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wordpress-operator
  namespace: external-wordpress-operator
spec:
  interval: 5m
  targetNamespace: external-wordpress-operator
  chart:
    spec:
      chart: ./packages/system/wordpress-operator
      sourceRef:
        kind: GitRepository
        name: external-apps
        namespace: cozy-public
      version: '*'
